<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>27ebb6b4-0b37-42ef-852d-7f0ad90e463d</testSuiteGuid>
   <testCaseLink>
      <guid>f45d6956-e870-4cde-95c9-26dca8f38ea1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC27- pedido sem desconto</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>050014f7-5847-4c75-a8e1-3a7d80d9df02</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/calcula pedido</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8418798-edd7-47c7-80db-50fd56c7f92b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a759a596-fd72-47aa-bf05-96ddbfa47ed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1796ca3-f122-40cb-b5c6-0d3d3180a5fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
