<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-account-root_LoginNome de usurio ou end_be4e66</name>
   <tag></tag>
   <elementGuidId>486a930d-7b97-4cf7-9de8-57e8c27ffec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-account-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-account-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-account-root</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginNome de usuário ou endereço de emailSenhaLoginEsqueci minha senha</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-account-root[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-account-root</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-account-root[(text() = 'LoginNome de usuário ou endereço de emailSenhaLoginEsqueci minha senha' or . = 'LoginNome de usuário ou endereço de emailSenhaLoginEsqueci minha senha')]</value>
   </webElementXpaths>
</WebElementEntity>
