<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CEP_fas fa-search info</name>
   <tag></tag>
   <elementGuidId>cdf574d3-4c7c-4401-9e0d-1a255b69e686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content-wrapper']/div/app-clientes-detail/form/div/div/div/div[14]/div/div/div/div/app-cep-search/button/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-search.info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-search info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/div[@class=&quot;container-fluid pt-2&quot;]/app-clientes-detail[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;d-flex row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;container p-3 my-3 border col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;align-self-center ml-2&quot;]/app-cep-search[1]/button[@class=&quot;btn btn-outline-light text-primary btn-sm ng-star-inserted&quot;]/div[@class=&quot;flex-row d-flex justify-content-around&quot;]/div[@class=&quot;pr-1&quot;]/i[@class=&quot;fas fa-search info&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/div/app-clientes-detail/form/div/div/div/div[14]/div/div/div/div/app-cep-search/button/div/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/i</value>
   </webElementXpaths>
</WebElementEntity>
