<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_aa30dda8-05ae-4b2f-aa92-c8c_7b9f2d</name>
   <tag></tag>
   <elementGuidId>2dfaf72e-f459-417b-8424-93efe7df65e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aa30dda8-05ae-4b2f-aa92-c8c7d9ec6565</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//id=&quot;03748570-ad72-4416-b987-7b46590de491&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aa30dda8-05ae-4b2f-aa92-c8c7d9ec6565</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa30dda8-05ae-4b2f-aa92-c8c7d9ec6565&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aa30dda8-05ae-4b2f-aa92-c8c7d9ec6565']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'aa30dda8-05ae-4b2f-aa92-c8c7d9ec6565']</value>
   </webElementXpaths>
</WebElementEntity>
