<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_f94ff1a7-6025-41cf-9ae9-aff_53fffe</name>
   <tag></tag>
   <elementGuidId>45d3b277-f5ad-490d-a72b-175fc8b986ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f94ff1a7-6025-41cf-9ae9-aff65916f75d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='f94ff1a7-6025-41cf-9ae9-aff65916f75d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f94ff1a7-6025-41cf-9ae9-aff65916f75d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f94ff1a7-6025-41cf-9ae9-aff65916f75d&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='f94ff1a7-6025-41cf-9ae9-aff65916f75d']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'f94ff1a7-6025-41cf-9ae9-aff65916f75d']</value>
   </webElementXpaths>
</WebElementEntity>
