<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__b76b75eb-e0f8-4b63-9ee8-ab8bc1998036</name>
   <tag></tag>
   <elementGuidId>cabbf65d-8536-4e03-92ce-e023db492cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b76b75eb-e0f8-4b63-9ee8-ab8bc1998036</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b76b75eb-e0f8-4b63-9ee8-ab8bc1998036']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b76b75eb-e0f8-4b63-9ee8-ab8bc1998036</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b76b75eb-e0f8-4b63-9ee8-ab8bc1998036&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b76b75eb-e0f8-4b63-9ee8-ab8bc1998036']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
