<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_3905a46f-52cd-40e6-a83f-b47_504f41</name>
   <tag></tag>
   <elementGuidId>5cb912f1-be07-4879-9b44-de0b4e616c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3905a46f-52cd-40e6-a83f-b471d9f01ea6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3905a46f-52cd-40e6-a83f-b471d9f01ea6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3905a46f-52cd-40e6-a83f-b471d9f01ea6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3905a46f-52cd-40e6-a83f-b471d9f01ea6&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3905a46f-52cd-40e6-a83f-b471d9f01ea6']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '3905a46f-52cd-40e6-a83f-b471d9f01ea6']</value>
   </webElementXpaths>
</WebElementEntity>
