<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_b75dd857-efd9-4b15-ae54-ee8_333526</name>
   <tag></tag>
   <elementGuidId>0b726f98-ef08-4f3c-b1d6-077c8946b3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b75dd857-efd9-4b15-ae54-ee81d117afbd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b75dd857-efd9-4b15-ae54-ee81d117afbd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b75dd857-efd9-4b15-ae54-ee81d117afbd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b75dd857-efd9-4b15-ae54-ee81d117afbd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b75dd857-efd9-4b15-ae54-ee81d117afbd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'b75dd857-efd9-4b15-ae54-ee81d117afbd']</value>
   </webElementXpaths>
</WebElementEntity>
