<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_d8c85390-5b8b-44ca-a1f7-19a_4840fb</name>
   <tag></tag>
   <elementGuidId>77221de8-2834-4bd8-be60-5fd19c303c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d8c85390-5b8b-44ca-a1f7-19a9e22652fd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d8c85390-5b8b-44ca-a1f7-19a9e22652fd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d8c85390-5b8b-44ca-a1f7-19a9e22652fd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d8c85390-5b8b-44ca-a1f7-19a9e22652fd&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d8c85390-5b8b-44ca-a1f7-19a9e22652fd']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd8c85390-5b8b-44ca-a1f7-19a9e22652fd']</value>
   </webElementXpaths>
</WebElementEntity>
