<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__d9da63c4-e2fd-45da-83cf-ac2599d9a1d7</name>
   <tag></tag>
   <elementGuidId>5fcb246d-c7ae-48b7-83bb-4eae8f81c337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d9da63c4-e2fd-45da-83cf-ac2599d9a1d7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d9da63c4-e2fd-45da-83cf-ac2599d9a1d7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d9da63c4-e2fd-45da-83cf-ac2599d9a1d7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d9da63c4-e2fd-45da-83cf-ac2599d9a1d7&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d9da63c4-e2fd-45da-83cf-ac2599d9a1d7']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
