<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bd5029a5-03f3-4b03-ae70-d4c67251c90e</name>
   <tag></tag>
   <elementGuidId>5c48808d-3558-444e-b119-38cfccc910a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bd5029a5-03f3-4b03-ae70-d4c67251c90e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bd5029a5-03f3-4b03-ae70-d4c67251c90e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bd5029a5-03f3-4b03-ae70-d4c67251c90e</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bd5029a5-03f3-4b03-ae70-d4c67251c90e&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bd5029a5-03f3-4b03-ae70-d4c67251c90e']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
