<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_9d90e9a8-a972-408e-bdc9-470a3e62c378</name>
   <tag></tag>
   <elementGuidId>00a1640d-b1c6-4a33-8220-8cb0eea01472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9d90e9a8-a972-408e-bdc9-470a3e62c378</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9d90e9a8-a972-408e-bdc9-470a3e62c378']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9d90e9a8-a972-408e-bdc9-470a3e62c378</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9d90e9a8-a972-408e-bdc9-470a3e62c378&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9d90e9a8-a972-408e-bdc9-470a3e62c378']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '9d90e9a8-a972-408e-bdc9-470a3e62c378']</value>
   </webElementXpaths>
</WebElementEntity>
