<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BATENTEPORTADIANT.DIREITOBRAS.VAR.79_n_45b1fc</name>
   <tag></tag>
   <elementGuidId>380bae75-9c87-4031-8d84-f1ddff656c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ngb-typeahead-2-4']/div/div/div/ngb-highlight/span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ngb-highlight ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-typeahead-2-4&quot;)/div[@class=&quot;m-1 ng-star-inserted&quot;]/div[@class=&quot;row p-2&quot;]/div[@class=&quot;mr-2&quot;]/ngb-highlight[1]/span[@class=&quot;ngb-highlight ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ngb-typeahead-2-4']/div/div/div/ngb-highlight/span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]/div/div/div/ngb-highlight/span[4]</value>
   </webElementXpaths>
</WebElementEntity>
