<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_5e1a6cbf-118c-4dca-81df-5e2_b71b98</name>
   <tag></tag>
   <elementGuidId>866a88fc-35a4-451e-a5a5-029ad318599a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5e1a6cbf-118c-4dca-81df-5e28fb721177</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='5e1a6cbf-118c-4dca-81df-5e28fb721177']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5e1a6cbf-118c-4dca-81df-5e28fb721177</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5e1a6cbf-118c-4dca-81df-5e28fb721177&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5e1a6cbf-118c-4dca-81df-5e28fb721177']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '5e1a6cbf-118c-4dca-81df-5e28fb721177']</value>
   </webElementXpaths>
</WebElementEntity>
