<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descontos_747dfcb8-bea6-4356-95a9-259_c16f59 (1)</name>
   <tag></tag>
   <elementGuidId>685af0ff-1102-4fa9-b3a0-c4f14020a277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#747dfcb8-bea6-4356-95a9-259d61f2a41f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='747dfcb8-bea6-4356-95a9-259d61f2a41f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>747dfcb8-bea6-4356-95a9-259d61f2a41f</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;747dfcb8-bea6-4356-95a9-259d61f2a41f&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='747dfcb8-bea6-4356-95a9-259d61f2a41f']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '747dfcb8-bea6-4356-95a9-259d61f2a41f']</value>
   </webElementXpaths>
</WebElementEntity>
