<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mayara Normandia_rounded-circle</name>
   <tag></tag>
   <elementGuidId>96427803-3f9b-41a2-876d-ef7aa0fc4262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='saudacaoUsuario']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src='assets/images/avatar.png';</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://172.16.1.21:7602/colaboradores/imagens/9722f77f-ea48-47cd-a833-a5fcd80d011c/e0b065da-3e15-44e2-be4c-5c2316358c49</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/nav[@class=&quot;d-flex navbar navbar-expand-lg navbar-light bg-light border-bottom&quot;]/div[@class=&quot;ml-auto&quot;]/app-menu-login[1]/div[@class=&quot;navbar-right&quot;]/ul[@class=&quot;navbar-nav mr-auto&quot;]/li[@class=&quot;nav-item dropdown ng-star-inserted&quot;]/div[@id=&quot;saudacaoUsuario&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/div[@class=&quot;mr-1 ml-2 ng-star-inserted&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='saudacaoUsuario']/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://172.16.1.21:7602/colaboradores/imagens/9722f77f-ea48-47cd-a833-a5fcd80d011c/e0b065da-3e15-44e2-be4c-5c2316358c49')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
