<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SFA - Fora de Vendas  DP INFORMTICA LTD_a6a7a3</name>
   <tag></tag>
   <elementGuidId>3cea0818-8da9-48f4-b582-6a8b490eede2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SFA - Força de Vendas  DP INFORMÁTICA LTDA - EPP                          DP INFORMÁTICA LTDA - EPP                         SairIndicadoresPedidosClientesProdutosTAXMinha conta Mayara Normandia                         Alterar imagemSairNovo Cliente Tipo Física JurídicaCPFRG* Razão SocialNome fantasiaAtivoInformações adicionaisTelefoneAdicionar TelefoneE-mailAdicionar E-mailEndereçoLogradouroNúmeroComplementoBairroCEPBuscar endereçoCidadeEstadoEndereços adicionaisAdicionar endereçoContatosAdicionar contatoVendedorValor mínimo para o pedidoCrédito Liberado Restrito BloqueadoTributosExceção FiscalEmpresa é orgão públicoPossui benefício de ICMS para SuframaPossui benefício de PIS e COFINS para SuframaDeduz PIS e COFINS de Suframa da Base de cálculo ICMSCancelarSalvar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wrapper']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
   </webElementXpaths>
</WebElementEntity>
